title: Об’єктно-орієнтоване програмування мовою Java
description: з використанням можливостей JavaFX для створення графічного інтерфейсу програмного продукту
show_downloads: true
theme: jekyll-theme-leap-day

github:
  zip_url: https://github.com/atmp-if/javafx/archive/0.3.zip
  pdf_url: https://github.com/atmp-if/javafx/releases/download/0.3/book.pdf
